version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    # labels:
    #   - automerge

  - package-ecosystem: npm
    directory: "/web/"
    versioning-strategy: lockfile-only
    schedule:
      interval: daily
      time: "00:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    # labels:
    #   - automerge

  - package-ecosystem: npm
    directory: "/web/remynify/"
    versioning-strategy: lockfile-only
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    # labels:
    #   - automerge

  - package-ecosystem: bundler
    directory: "/web/jekyll/"
    versioning-strategy: lockfile-only
    schedule:
      interval: daily
      time: "01:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    # labels:
    #   - automerge

  - package-ecosystem: npm
    directory: "/production-test/"
    versioning-strategy: lockfile-only
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    # labels:
    #   - automerge

  - package-ecosystem: npm
    directory: "/backstop/"
    versioning-strategy: lockfile-only
    schedule:
      interval: daily
      time: "02:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    # labels:
    #   - automerge
