version: 2

updates:
  - package-ecosystem: npm
    directory: "/web/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    open-pull-requests-limit: 10
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  - package-ecosystem: bundler
    directory: "/web/jekyll/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    open-pull-requests-limit: 10
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
