version: 2

updates:
  - package-ecosystem: npm
    directory: "/web/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  - package-ecosystem: bundler
    directory: "/web/jekyll/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  - package-ecosystem: npm
    directory: "/analytics/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
