language: generic

addons:
  apt:
    update: true
    packages:
      - ruby
      - pandoc
      - imagemagick
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true
  include:
    - { os: linux }
    - { os: osx, if: branch == master }

install:
  - |
    if [ "$(uname -s)" = Linux ]; then
      nvm install
    fi

  - |
    which node
    which npm
    node --version
    npm --version

  - |
    if [ "$(uname -s)" = Darwin ]; then
      brew upgrade node
      nvm alias default system
      nvm use default
    fi

  - |
    which node
    which npm
    node --version
    npm --version

script:
  - make
