[build]
  publish = "."
  command = "true"

[[headers]]
  for = "/*"

  [headers.values]
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://matejkosiarcik.report-uri.com/a/d/g"}],"include_subdomains":true}'

    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.matejkosiarcik.com; base-uri 'self'; script-src 'self' 'unsafe-inline' https://*.matejkosiarcik.com https://polyfill.io; object-src 'none'; form-action 'none'; frame-src 'none'; frame-ancestors 'none'; require-sri-for script style; block-all-mixed-content; report-uri https://matejkosiarcik.report-uri.com/r/d/csp/enforce; report-to default;"

    # disable all
    Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'none'; usb 'none'; vibrate 'none'; vr 'none'"
