name: Build and Deploy

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Setup nodeJS ğŸ§©
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'

      - name: Setup ruby ğŸ§©
        uses: ruby/setup-ruby@v1.64.1
        with:
          ruby-version: '2.7'

      - name: Build ğŸ”§
        run: |
          cd web
          make bootstrap build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages
          FOLDER: web/public
          COMMIT_MESSAGE: "deploy: website go brrr ğŸš€ [ci skip]"
          CLEAN: true
          SINGLE_COMMIT: true
