name: Build and Deploy

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

# TODO: setup dependabot to update actions
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Setup nodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Build ğŸ”§
        run: |
          cd web
          make bootstrap build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages
          FOLDER: web/public
          CLEAN: true
